name: run main.py

on:
  #push
  schedule:
    - cron: '1,31 12-23 * * *'
    - cron: '1,31 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4' # install the python version needed
          
      - name: install libcurl4
        run: |
          sudo apt-get update
          sudo apt install libcurl4-openssl-dev libssl-dev
        shell: bash

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: python main.py
